Avoid missing library for opencv.
This is the error that it solved:

Traceback (most recent call last):
  File "../../../src/tools/align_buildings.py", line 4, in <module>
    import cv2
ImportError: libx264.so.138: cannot open shared object file: No such file or directory