pubgeo-tools: Depend on conda-forge pdal package
Replace dependency on libpdal from the kitware-geospatial package with a
dependency on the pdal package from conda-forge.

Apply a patch to compile with PDAL 1.7. Upstream assumes an older
version.

Apply a patch to fix errors linking with the conda-forge PDAL. The
errors are like:

    src/common/libPUBGEO_LIB.a(PointCloud.cpp.o): In function `pubgeo::PointCloud::TransformPointCloud(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, float, float)':
    PointCloud.cpp:(.text+0xc6f): undefined reference to `pdal::PipelineExecutor::PipelineExecutor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'